# Execute with 'snapcraft' when inside the project's root folder.
# The resulting snap can then be installed with 'sudo snap install lanpush-cli_x.y.z_amd64.snap' # additional flags for development:--devmode --dangerous
# To publish the snap, run 'snapcraft push lanpush-cli_<version>_<arch>.snap'

name: lanpush # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '1.0.6'
summary: Utility to exchange text messages between devices in the same local network.
description: |
  This is the CLI version (terminal only) client for LANPUSH.
  With LANPUSH all devices in the same LAN can read and write messages between themselves.
  No internet or login required!
  Run "lanpush --help" for usage info.

grade: stable # must be 'stable' to release into candidate/stable channels, or 'devel' to release into development channels
confinement: strict # use 'strict' once you have the right plugs and slots, or 'devmode' for development only

apps:
  lanpush:
    command: lanpush-cli.sh
    plugs:
      - network
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/default-java
      PATH: $JAVA_HOME/bin:$PATH

# --- CONFIGURATION FOR LOCAL BUILD ---
parts:
  lanpush:   
    plugin: dump
    source: target/
    build-packages:
      - ca-certificates
      - ca-certificates-java
    stage-packages:
       - default-jre-headless
    override-build: |
      snapcraftctl build
      rm $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-amd64/lib/security/blacklisted.certs # removing symlink to external file
  
  launcher:
    plugin: dump
    source: snap/local/
    
# --- CONFIGURATION FOR MAVEN BUILD FROM REPOSITORY ---
# MAVEN WAS DISCONTINUED IN CORE 20, BUT IS COMING BACK IN CORE 22 (NOT STABLE YET)
# DISCUSSION: https://forum.snapcraft.io/t/maven-plugin-missing-in-core20/29044/15
# parts:
#   lanpush-cli:
#     plugin: maven
#     source: https://github.com/leandrocm86/lanpush-cli.git
#     source-type: git
#     # source_tag: master
#     maven-parameters: # maven-options (core 18) changed to maven-parameters (core 22)
#       [-DskipTests=true]
#     organize:
#       ../target/: target/
#       ../snap/local/: wrapper/
#     build-packages:
#       - default-jdk-headless
#       - maven
#     stage-packages:
#       - default-jre-headless
